name = "caoliao-feishu-connector"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
CAOLIAO_API_KEY = ""
FEISHU_APP_ID = ""
FEISHU_APP_SECRET = ""
